import React, { useState, useEffect, useRef } from 'react';
import MessageBubble from './components/MessageBubble';
import InputBox from './components/InputBox';
import SystemStatus from './components/SystemStatus';
import { sendMessage, checkBackendStatus } from './services/api';
import { Cpu } from 'lucide-react';

function App() {
  const [messages, setMessages] = useState([
    { role: 'assistant', content: "Hello! I'm your system diagnostics AI. Ask me about your computer's health." }
  ]);
  const [loading, setLoading] = useState(false);
  const [backendStatus, setBackendStatus] = useState('Checking...');
  const chatEndRef = useRef(null);

  const scrollToBottom = () => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  useEffect(() => {
    const checkStatus = async () => {
      const res = await checkBackendStatus();
      setBackendStatus(res.status || 'Offline');
    };
    checkStatus();
    const interval = setInterval(checkStatus, 10000);
    return () => clearInterval(interval);
  }, []);

  const handleSend = async (text) => {
    const userMsg = { role: 'user', content: text };
    setMessages(prev => [...prev, userMsg]);
    setLoading(true);

    try {
      const response = await sendMessage(text);
      const aiMsg = { 
        role: 'assistant', 
        content: response.response,
        data: response.data_collected
      };
      setMessages(prev => [...prev, aiMsg]);
    } catch (error) {
      setMessages(prev => [...prev, { role: 'assistant', content: "Sorry, I couldn't reach the system agent. Is the backend running?" }]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex h-screen bg-zinc-950 text-white font-sans overflow-hidden">
      {/* Sidebar (Visual only for now) */}
      <div className="w-64 border-r border-zinc-800 p-4 hidden md:flex flex-col gap-4">
        <div className="flex items-center gap-2 mb-6 text-blue-400">
          <Cpu className="w-6 h-6" />
          <h1 className="font-bold text-lg tracking-tight">SystemMind</h1>
        </div>

        <div className="flex-1">
          <div className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-3">Sessions</div>
          <div className="p-2 bg-zinc-900 rounded-lg text-sm text-zinc-300 border border-zinc-800 cursor-pointer hover:border-zinc-700 transition-colors">
            Current Session
          </div>
        </div>

        <SystemStatus status={backendStatus} />
      </div>

      {/* Main Chat Area */}
      <div className="flex-1 flex flex-col max-w-4xl mx-auto w-full">
        {/* Header (Mobile only) */}
        <div className="md:hidden p-4 border-b border-zinc-800 flex justify-between items-center">
          <span className="font-bold flex items-center gap-2"><Cpu className="w-5 h-5" /> SystemMind</span>
          <SystemStatus status={backendStatus} />
        </div>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-4 md:p-8 space-y-4 scrollbar-thin scrollbar-thumb-zinc-700 scrollbar-track-transparent">
          {messages.map((msg, idx) => (
            <MessageBubble key={idx} role={msg.role} content={msg.content} data={msg.data} />
          ))}
          {loading && (
            <div className="flex justify-start animate-pulse">
              <div className="bg-zinc-800 px-4 py-3 rounded-2xl rounded-bl-none text-zinc-400 text-sm">
                Analyzing system...
              </div>
            </div>
          )}
          <div ref={chatEndRef} />
        </div>

        {/* Input Area */}
        <div className="p-4 md:p-6 pb-6 md:pb-8">
          <InputBox onSend={handleSend} disabled={loading} />
          <p className="text-center text-zinc-600 text-xs mt-3">
            SystemMind checks live metrics. Responses generated by AI.
          </p>
        </div>
      </div>
    </div>
  );
}

export default App;
